version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  tests:
    build: .
    command: bash -c 'pytest tests/ && pytest --cov=allocation --cov-report=xml'
    volumes:
      - .:/code

  linters:
    build: .
    command: bash -c 'pip install --upgrade pip && pip install -r requirements-dev.txt && flake8'
    volumes:
      - .:/code

  mypy:
    build: .
    command: bash -c 'pip install --upgrade pip && pip install -r requirements-dev.txt && mypy .'
    volumes:
      - .:/code

  fill_db:
    build: .
    command: bash -c 'python manage.py migrate && python manage.py loaddata output.json'
    volumes:
      - .:/code
