# Generated by Django 4.0.6 on 2022-08-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoilDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, verbose_name='Идентификатор бухты')),
                ('product_id', models.CharField(max_length=255, verbose_name='Идентификатор материала')),
                ('quantity', models.IntegerField(verbose_name='Изначальное количество')),
                ('recommended_balance', models.IntegerField(verbose_name='Рекомендуемый остаток')),
                ('acceptable_loss', models.IntegerField(verbose_name='Приемлемые потери')),
            ],
            options={
                'verbose_name': 'Бухта',
                'verbose_name_plural': 'Бухты',
            },
        ),
        migrations.CreateModel(
            name='OrderLineDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, verbose_name='Идентификатор заказа')),
                ('line_item', models.CharField(max_length=255, verbose_name='Номер товарной позиции в заказе')),
                ('product_id', models.CharField(max_length=255, verbose_name='Идентификатор материала')),
                ('quantity', models.IntegerField(verbose_name='Количество материала')),
            ],
            options={
                'verbose_name': 'Товарная позиция',
                'verbose_name_plural': 'Товарные позиции',
            },
        ),
        migrations.CreateModel(
            name='AllocationDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.coildb', verbose_name='Идентификатор бухты')),
                ('orderline_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.orderlinedb', verbose_name='Идентификатор товарной позиции')),
            ],
            options={
                'verbose_name': 'Размещение товарной позиции',
                'verbose_name_plural': 'Размещения товарных позиций',
            },
        ),
    ]
