# Generated by Django 4.0.4 on 2022-05-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('recommended_balance', models.IntegerField()),
                ('acceptable_loss', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.coil')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.orderline')),
            ],
        ),
    ]
